### ISSUE TITLE
在iOS 8 系统下崩溃

### ISSUE THREAD

**Issue by HZRZCW** [JohnnyHooo/HJViewStyle#4]
崩溃报错：*** -[_UIToolbarBackground shadowView]: message sent to deallocated instance 0x7fef606c24d0

![image](https://user-images.githubusercontent.com/12219811/51319585-701fe380-1a98-11e9-8903-123fc53777eb.png)

**Comment by JohnnyHooo** [comment]
抱歉.最低兼容版本暂未测试iOS8.最低兼容是iOS9
