### ISSUE TITLE
对button 阴影和切圆角不能共存

### ISSUE THREAD

**Issue by zengjinzong** [JohnnyHooo/HJViewStyle#8]

**Comment by JohnnyHooo** [comment]
可以提供代码吗？

**Comment by zengjinzong** [comment]
//代码示例
    UIButton *label = [UIButton new];
    label.frame = CGRectMake(10, 400, 200, 50);
    label.backgroundColor = UIColor.redColor;
    
    label.shadowRadius = 10;
    label.shadowColor = UIColor.blackColor;
    label.shadowOffset = CGSizeMake(0, 0);
    label.shadowOpacity = 1;
    
    label.cornerRadius = 20;
    label.borderColor = UIColor.yellowColor;
    label.borderWidth = 10;

    [self.view addSubview:label];

**Comment by JohnnyHooo** [comment]
谢谢反馈，1.2.0版本已修复。
